---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: apiscout
  name: apiscout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apiscout
  template:
    metadata:
      labels:
        run: apiscout
    spec:
      containers:
      - name: apiscout
        image: naresh/apiscout:latest
        env:
        - name: MODE
          value: "KUBE"
        - name: HUGODIR
          value: "/tmp"
        - name: EXTERNALIP
          value: "192.168.99.100"
        - name:  USERNAME
          value: "yaminisailakshmi"
        - name: PASSWORD
          value: "sailakshmi2793"
        - name: APIKEY
          value: "wpu3755m2c9s9329dgn9j4mh"
        - name: APISECRETE
          value: "vv4jdQHCvy"
        - name: AREAID
          value: "9c824242-ac7e-4b40-8010-64fed84eac6e"
        - name: AREADOMAIN
          value: "trial1048.api.mashery.com"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: apiscout-svc
  name: apiscout-svc
  namespace: default
spec:
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 80
  selector:
    run: apiscout
  type: LoadBalancer